#!/bin/bash

#####################
# Autocomplete
#####################

if type brew &>/dev/null; then
  BREW_PREFIX="$(brew --prefix)"
  if [[ -r "${BREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${BREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for completion_script in "${BREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "${completion_script}" ]] && source "${completion_script}"
    done
  fi

  # gcloud
  [ -f "${BREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc" ] \
    && source "${BREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"
fi

# Setup kubectl completion and completions for the alias 'k'
command -v kubectl > /dev/null 2>&1 && source <(kubectl completion bash | sed 's/kubectl/k/g')
# Setup autocompletion for kind cluster utility
command -v kind > /dev/null 2>&1 && source <(kind completion bash)
# Setup autocompletion for 
command -v kind > /dev/null 2>&1 && source <(flux completion bash)
