#!/bin/bash

#####################
# Autocomplete
#####################

if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for completion_script in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "${completion_script}" ]] && source "${completion_script}"
    done
  fi
fi

# gcloud
[ -f "${HOMEBREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc" ] \
  && source "${HOMEBREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"

# Setup kubectl completion and completions for the alias 'k'
command -v kubectl > /dev/null 2>&1 && source <(kubectl completion bash | sed 's/kubectl/k/g')
# Setup autocompletion for kind cluster utility
command -v kind > /dev/null 2>&1 && source <(kind completion bash)

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && source "/opt/homebrew/opt/nvm/nvm.sh" # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && source "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
