#!/bin/bash

########################################
# Fuzzy searching
########################################
FZF_PATH="/usr/local/opt/fzf"
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -d "$HOMEBREW_PREFIX" ]]; then
    FZF_PATH="$HOMEBREW_PREFIX/opt/fzf"
  fi
fi
export PATH="$PATH:$FZF_PATH/bin"

# Auto-completion
[[ $- == *i* ]] && source "${FZF_PATH}/shell/completion.bash" 2> /dev/null
# Key bindings
source "${FZF_PATH}/shell/key-bindings.bash"

# fzf + ag configuration
export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='
--color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
--color info:108,prompt:109,spinner:108,pointer:168,marker:168
'
