#!/bin/zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

brew install kube-ps1

tee -a "$HOME/.zshrc" <<EOF
source \${DOTFILES_LOCATION}/shell/profile
source \${DOTFILES_LOCATION}/shell/zsh/history
EOF
